### ISSUE TITLE
Max velocity chosen on graph is not correct

### ISSUE THREAD

**Issue by JennR1990** [thartbm/PySelector#28]

**Comment by thartbm** [comment]
Core functionality. Should work exactly like in the Matlab version, this is how I remember it:

0: Take ALL the samples for the reach, not just the ones between P1 and P2, this gives better estimates and saves some computation that now just has to be done when opening the trial.
1: Spline interpolate both the X and Y coordinates of the trajectory over time, so that the sampling interval/rate is constant.
2: Apply the bi-directional Butterworth filter to both the X and Y coordinates (using the constant sampling rate that you just calculated).
3: Now calculate the velocity profile, and store it somewhere.
4: Use THE SMOOTHED VELOCITY to guestimate max velocity, AND to plot the velocity profile.
5: If the use changes P1/P2 or selects a different max velocity, you use the stored velocity profile to generate the new plot.

Please make this work.
